<?php

use App\Enums\CustomFieldType;
use App\Models\CustomField;
use App\Models\CustomFieldValue;
use App\Models\Member;
use App\Models\Opportunity;
use App\Models\Store;
use App\Models\User;
use Database\Seeders\PermissionSeeder;
use Database\Seeders\RoleSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Volt\Volt;

uses(RefreshDatabase::class);

/*
|--------------------------------------------------------------------------
| Opportunity create/edit form — header fields (M8-3a)
|--------------------------------------------------------------------------
|
| The single Volt form serves opportunities.create and opportunities.edit. It
| builds a Create/Update DTO from form state and calls the SAME action classes
| the API uses (CreateOpportunity / UpdateOpportunity), which own the gate
| check. These tests assert the form persists through the real action pipeline,
| surfaces validation, round-trips custom fields, hides create-only fields on
| edit, and is gated on opportunities.create / opportunities.edit.
|
*/

beforeEach(function () {
    config(['signals.installed' => true, 'signals.setup_complete' => true]);
    $this->seed(PermissionSeeder::class);
    $this->seed(RoleSeeder::class);
    $this->owner = User::factory()->owner()->create();
    $this->store = Store::factory()->create(['timezone' => 'UTC']);
});

it('renders the create form for a user with opportunities.create', function () {
    $this->actingAs($this->owner);

    Volt::test('opportunities.form')
        ->assertOk()
        ->assertSee('New Opportunity')
        ->assertSee('Create Opportunity');
});

it('forbids the create form for a user without opportunities.create', function () {
    $viewer = User::factory()->create();
    $viewer->givePermissionTo('opportunities.access', 'opportunities.view');
    $this->actingAs($viewer);

    Volt::test('opportunities.form')->assertForbidden();
});

it('persists a new opportunity through the CreateOpportunity action and redirects', function () {
    $member = Member::factory()->create();
    $this->actingAs($this->owner);

    Volt::test('opportunities.form')
        ->set('subject', 'Festival Hire')
        ->set('storeId', $this->store->id)
        ->set('memberId', $member->id)
        ->set('reference', 'PO-9001')
        ->call('save')
        ->assertHasNoErrors()
        ->assertRedirect();

    $opportunity = Opportunity::query()->where('subject', 'Festival Hire')->first();

    expect($opportunity)->not->toBeNull()
        ->and($opportunity->store_id)->toBe($this->store->id)
        ->and($opportunity->member_id)->toBe($member->id)
        ->and($opportunity->reference)->toBe('PO-9001')
        // The number is auto-generated by OpportunityNumberGenerator, never an input.
        ->and($opportunity->number)->not->toBeNull();
});

it('surfaces a validation error when the subject is empty', function () {
    $this->actingAs($this->owner);

    Volt::test('opportunities.form')
        ->set('subject', '')
        ->call('save')
        ->assertHasErrors(['subject' => 'required']);

    expect(Opportunity::query()->count())->toBe(0);
});

it('round-trips a custom field value on create', function () {
    CustomField::factory()->create([
        'module_type' => 'Opportunity',
        'name' => 'po_reference',
        'display_name' => 'PO Reference',
        'field_type' => CustomFieldType::String,
    ]);

    $this->actingAs($this->owner);

    Volt::test('opportunities.form')
        ->set('subject', 'Custom Field Opp')
        ->set('storeId', $this->store->id)
        ->set('customFieldValues.po_reference', 'PO-555')
        ->call('save')
        ->assertHasNoErrors()
        ->assertRedirect();

    $opportunity = Opportunity::query()->where('subject', 'Custom Field Opp')->firstOrFail();

    $value = CustomFieldValue::query()
        ->where('entity_type', $opportunity->getMorphClass())
        ->where('entity_id', $opportunity->id)
        ->where('value_string', 'PO-555')
        ->exists();

    expect($value)->toBeTrue();
});

it('loads the edit form with the existing header values', function () {
    $opportunity = Opportunity::factory()->create([
        'subject' => 'Editable Opp',
        'store_id' => $this->store->id,
        'reference' => 'REF-EDIT',
    ]);

    $this->actingAs($this->owner);

    Volt::test('opportunities.form', ['opportunity' => $opportunity])
        ->assertSet('subject', 'Editable Opp')
        ->assertSet('storeId', $this->store->id)
        ->assertSet('reference', 'REF-EDIT')
        ->assertOk()
        ->assertSee('Save Changes');
});

it('updates an existing opportunity through the UpdateOpportunity action', function () {
    $opportunity = Opportunity::factory()->create([
        'subject' => 'Old Subject',
        'store_id' => $this->store->id,
    ]);

    $this->actingAs($this->owner);

    Volt::test('opportunities.form', ['opportunity' => $opportunity])
        ->set('subject', 'New Subject')
        ->set('reference', 'REF-NEW')
        ->call('save')
        ->assertHasNoErrors()
        ->assertRedirect(route('opportunities.show', $opportunity->id));

    $fresh = $opportunity->fresh();

    expect($fresh->subject)->toBe('New Subject')
        ->and($fresh->reference)->toBe('REF-NEW');
});

it('persists the schedule & logistics fields through the form (C-data-1)', function () {
    $this->actingAs($this->owner);

    Volt::test('opportunities.form')
        ->set('subject', 'Scheduled Hire')
        ->set('storeId', $this->store->id)
        ->set('deliverStartsAt', '2026-07-02 08:00')
        ->set('collectEndsAt', '2026-07-06 13:00')
        ->set('orderedAt', '2026-06-15 09:30')
        ->set('useChargeableDays', true)
        ->set('chargeableDays', '2.5')
        ->set('openEndedRental', true)
        ->set('customerCollecting', true)
        ->set('customerReturning', true)
        ->set('deliveryInstructions', 'Gate B')
        ->set('collectionInstructions', 'Bay 3')
        ->call('save')
        ->assertHasNoErrors()
        ->assertRedirect();

    $opportunity = Opportunity::query()->where('subject', 'Scheduled Hire')->firstOrFail();

    expect($opportunity->deliver_starts_at)->not->toBeNull()
        ->and($opportunity->collect_ends_at)->not->toBeNull()
        ->and($opportunity->ordered_at)->not->toBeNull()
        ->and((bool) $opportunity->use_chargeable_days)->toBeTrue()
        ->and((string) $opportunity->chargeable_days)->toBe('2.5')
        ->and((bool) $opportunity->open_ended_rental)->toBeTrue()
        ->and((bool) $opportunity->customer_collecting)->toBeTrue()
        ->and((bool) $opportunity->customer_returning)->toBeTrue()
        ->and($opportunity->delivery_instructions)->toBe('Gate B')
        ->and($opportunity->collection_instructions)->toBe('Bay 3');
});

it('hides the prices_include_tax checkbox on the edit form (create-only)', function () {
    $opportunity = Opportunity::factory()->create(['store_id' => $this->store->id]);

    $this->actingAs($this->owner);

    // The editable checkbox label is only present on create; edit shows a
    // read-only badge instead.
    Volt::test('opportunities.form', ['opportunity' => $opportunity])
        ->assertDontSee('Set at creation only.');
});

it('forbids the edit form for a user without opportunities.edit', function () {
    $opportunity = Opportunity::factory()->create();

    $viewer = User::factory()->create();
    $viewer->givePermissionTo('opportunities.access', 'opportunities.view');
    $this->actingAs($viewer);

    Volt::test('opportunities.form', ['opportunity' => $opportunity])->assertForbidden();
});

it('selects a member via the autocomplete picker', function () {
    $member = Member::factory()->create(['name' => 'Acme Events Ltd', 'is_active' => true]);

    $this->actingAs($this->owner);

    Volt::test('opportunities.form')
        ->set('memberSearch', 'Acme')
        ->call('selectMember', $member->id)
        ->assertSet('memberId', $member->id)
        ->assertSet('memberSelectedName', 'Acme Events Ltd')
        ->assertSet('memberSearch', '');
});

it('creates a new address on the member and selects it into the delivery FK', function () {
    $member = Member::factory()->organisation()->create(['is_active' => true]);
    $this->actingAs($this->owner);

    $component = Volt::test('opportunities.form')
        ->set('memberId', $member->id)
        ->call('selectMember', $member->id)
        ->call('openAddressModal', 'delivery')
        ->assertSet('showAddressModal', true)
        ->assertSet('addressTarget', 'delivery')
        ->set('newAddressStreet', '12 Stage Lane')
        ->set('newAddressCity', 'Leeds')
        ->set('newAddressWhat3words', 'index.home.raft')
        ->call('saveNewAddress')
        ->assertHasNoErrors()
        ->assertSet('showAddressModal', false);

    $address = $member->addresses()->first();

    expect($address)->not->toBeNull()
        ->and($address->street)->toBe('12 Stage Lane')
        ->and($address->what3words)->toBe('index.home.raft');

    // The freshly-created address is selected into the delivery FK.
    $component->assertSet('deliveryAddressId', $address->id);
});

it('validates the required street when adding a new address', function () {
    $member = Member::factory()->organisation()->create(['is_active' => true]);
    $this->actingAs($this->owner);

    Volt::test('opportunities.form')
        ->set('memberId', $member->id)
        ->call('selectMember', $member->id)
        ->call('openAddressModal', 'collection')
        ->call('saveNewAddress')
        ->assertHasErrors(['newAddressStreet' => 'required'])
        ->assertSet('showAddressModal', true);

    expect($member->addresses()->count())->toBe(0);
});

it('drops a stale address selection when the member changes', function () {
    [$memberA, $memberB] = [
        Member::factory()->organisation()->create(['is_active' => true]),
        Member::factory()->organisation()->create(['is_active' => true]),
    ];
    $address = $memberA->addresses()->create(['street' => 'A Road', 'name' => 'A']);
    $this->actingAs($this->owner);

    $component = Volt::test('opportunities.form')
        ->call('selectMember', $memberA->id)
        ->set('deliveryAddressId', $address->id)
        ->assertSet('deliveryAddressId', $address->id);

    // Switching to a member that does not own that address clears the selection.
    $component->call('selectMember', $memberB->id)
        ->assertSet('deliveryAddressId', null);
});
